# Generated by Django 5.1 on 2024-08-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Computer', 'Computer'), ('Mobile', 'Mobile')], max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('code', models.TextField()),
                ('linenos', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('python', 'python'), ('java', 'java'), ('C', 'C'), ('C++', 'C++'), ('JavaScript', 'JavaScript')], default='python', max_length=100)),
                ('style', models.CharField(choices=[('friendly', 'friendly'), ('angry', 'angry')], default='friendly', max_length=100)),
            ],
        ),
    ]
